### ISSUE TITLE
click code to add comment

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenReview#48]
click on code line to add comment, like on github? is it even possible as IE runs in quirks mode?

**Comment by germanysources** [comment]
I started working on this. `abapOpenReview` is still the best tool for cross-package changes.

**Comment by larshp** [comment]
feel free

I've more or less abandoned this project, and instead using git pull requests for reviews. I personally would like to implement the Pull Request feature in abapGitServer for customers that do not have access to a git server. 

I've invited you as a collaborator 👍

**Comment by germanysources** [comment]
Feature implemented.
