### ISSUE TITLE
Is ABAP-Logger dependency necessary?

### ISSUE THREAD

**Issue by jrodriguez-rc** [larshp/abapOpenReview#55]
Checking ABAP-Logger dependency, it is used, but the log is never saved or displayed.

Is this dependency necessary?

**Comment by larshp** [comment]
#54, @germanysources

**Comment by germanysources** [comment]
@ jrodriguez-rc 
The logger should record exceptions when fetching enhancement diffs. Instead of using this dependency we can display something like this in the diff section
```
ENHO ZSAMPLE_ENHO 1
Failed to retrieve the diff. Reason:
(exception text)
```

**Comment by germanysources** [comment]
The dependency was removed and replaced by a inline message.
